package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/Avalanche-io/c4"
	"github.com/Avalanche-io/c4/c4m"
	c4store "github.com/Avalanche-io/c4/store"
)

// runPool implements "c4sh pool <c4m> <dir>" — bundle a c4m file with all
// its referenced store objects into a self-contained portable directory.
//
// Result:
//
//	<dir>/
//	  <name>.c4m       (copy of the manifest)
//	  store/           (TreeStore with only referenced objects)
//	  extract.sh       (self-extracting shell script)
func runPool(args []string) {
	if len(args) < 2 {
		die("pool: usage: c4sh pool <file.c4m> <output-dir>")
	}

	c4mPath := args[0]
	if !strings.HasSuffix(c4mPath, ".c4m") {
		if _, err := os.Stat(c4mPath + ".c4m"); err == nil {
			c4mPath += ".c4m"
		}
	}

	outDir := args[1]

	// Load manifest
	m, err := loadManifest(c4mPath)
	if err != nil {
		die("pool: %v", err)
	}

	// Open source store
	src, err := openStore()
	if err != nil {
		die("pool: %v", err)
	}

	// Create output directory and pool store
	poolStorePath := filepath.Join(outDir, "store")
	dst, err := c4store.NewTreeStore(poolStorePath)
	if err != nil {
		die("pool: create pool store: %v", err)
	}

	// Copy referenced objects
	var copied, skipped, missing int
	seen := make(map[c4.ID]bool)

	for _, e := range m.Entries {
		if e.C4ID.IsNil() || seen[e.C4ID] {
			continue
		}
		seen[e.C4ID] = true

		if dst.Has(e.C4ID) {
			skipped++
			continue
		}

		rc, err := src.Open(e.C4ID)
		if err != nil {
			fmt.Fprintf(os.Stderr, "c4sh: pool: missing %s (%s)\n", e.C4ID, entryName(m, e))
			missing++
			continue
		}

		if _, err := dst.Put(rc); err != nil {
			rc.Close()
			die("pool: store %s: %v", e.C4ID, err)
		}
		rc.Close()
		copied++
	}

	// Copy the c4m file
	c4mDest := filepath.Join(outDir, filepath.Base(c4mPath))
	if err := copyFile(c4mPath, c4mDest); err != nil {
		die("pool: copy manifest: %v", err)
	}

	// Generate self-extracting script
	if err := writeExtractScript(outDir, filepath.Base(c4mPath), m); err != nil {
		fmt.Fprintf(os.Stderr, "c4sh: pool: warning: could not write extract.sh: %v\n", err)
	}

	fmt.Printf("Pool: %d objects copied, %d skipped, %d missing\n", copied, skipped, missing)
	if missing > 0 {
		os.Exit(1)
	}
}

// entryName returns a short display name for an entry (for error messages).
func entryName(m *c4m.Manifest, e *c4m.Entry) string {
	return entryFullPath(m, e)
}

// copyFile copies a regular file.
func copyFile(src, dst string) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0755); err != nil {
		return err
	}
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()

	if _, err := io.Copy(out, in); err != nil {
		return err
	}
	return out.Sync()
}

// writeExtractScript generates a portable shell script that materializes
// the c4m contents using only standard Unix tools — no c4 installation required.
func writeExtractScript(outDir, c4mName string, m *c4m.Manifest) error {
	scriptPath := filepath.Join(outDir, "extract.sh")
	f, err := os.OpenFile(scriptPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0755)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintf(f, "#!/bin/sh\n")
	fmt.Fprintf(f, "# Self-extracting script for %s\n", c4mName)
	fmt.Fprintf(f, "# Generated by c4sh pool — no c4 installation required.\n")
	fmt.Fprintf(f, "set -e\n")
	fmt.Fprintf(f, "DIR=\"$(cd \"$(dirname \"$0\")\" && pwd)\"\n")
	fmt.Fprintf(f, "STORE=\"$DIR/store\"\n")
	fmt.Fprintf(f, "OUT=\"${1:-./%s}\"\n", strings.TrimSuffix(c4mName, ".c4m"))
	fmt.Fprintf(f, "echo \"Extracting %s to $OUT ...\"\n", c4mName)

	// Build directory creation commands and file copy commands
	var dirStack []string
	for _, e := range m.Entries {
		fullPath := buildPath(dirStack, e)

		if e.IsDir() {
			// Track directory stack by depth
			for len(dirStack) > e.Depth {
				dirStack = dirStack[:len(dirStack)-1]
			}
			dirStack = append(dirStack, strings.TrimSuffix(e.Name, "/"))
			fmt.Fprintf(f, "mkdir -p \"$OUT/%s\"\n", fullPath)
			continue
		}

		if e.C4ID.IsNil() {
			continue
		}

		// Find the store path for this ID using trie walk
		idStr := e.C4ID.String()
		fmt.Fprintf(f, "cp \"$(find \"$STORE\" -name '%s' -print -quit 2>/dev/null)\" \"$OUT/%s\"\n", idStr, fullPath)
	}

	fmt.Fprintf(f, "echo \"Done. %d entries extracted.\"\n", len(m.Entries))
	return nil
}

// buildPath reconstructs a file path from the directory stack and entry.
func buildPath(dirStack []string, e *c4m.Entry) string {
	parts := make([]string, 0, len(dirStack)+1)
	for i := 0; i < e.Depth && i < len(dirStack); i++ {
		parts = append(parts, dirStack[i])
	}
	parts = append(parts, strings.TrimSuffix(e.Name, "/"))
	return filepath.Join(parts...)
}
