package main

import (
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/Avalanche-io/c4"
	"github.com/Avalanche-io/c4/c4m"
	c4store "github.com/Avalanche-io/c4/store"
)

// poolResult holds counters from a pool operation.
type poolResult struct {
	Copied  int
	Skipped int
	Missing int
}

// runPool implements "c4sh pool <c4m> <dir>" — bundle a c4m file with all
// its referenced store objects into a self-contained portable directory.
//
// Result:
//
//	<dir>/
//	  <name>.c4m       (copy of the manifest)
//	  store/           (TreeStore with only referenced objects)
//	  extract.sh       (self-extracting shell script)
func runPool(args []string) {
	if len(args) < 2 {
		die("pool: usage: c4sh pool <file.c4m> <output-dir>")
	}

	c4mPath := args[0]
	if !strings.HasSuffix(c4mPath, ".c4m") {
		if _, err := os.Stat(c4mPath + ".c4m"); err == nil {
			c4mPath += ".c4m"
		}
	}

	outDir := args[1]

	// Load manifest
	m, err := loadManifest(c4mPath)
	if err != nil {
		die("pool: %v", err)
	}

	// Open source store
	src, err := openStore()
	if err != nil {
		die("pool: %v", err)
	}

	res, err := poolManifest(m, src, c4mPath, outDir)
	if err != nil {
		die("pool: %v", err)
	}

	fmt.Printf("Pool: %d objects copied, %d skipped, %d missing\n", res.Copied, res.Skipped, res.Missing)
	if res.Missing > 0 {
		osExit(1)
	}
}

// poolManifest bundles a manifest and its store objects into outDir.
// It copies referenced objects from src into a new TreeStore at outDir/store,
// copies the c4m file, and generates extract.sh.
func poolManifest(m *c4m.Manifest, src c4store.Store, c4mPath, outDir string) (poolResult, error) {
	poolStorePath := filepath.Join(outDir, "store")
	dst, err := c4store.NewTreeStore(poolStorePath)
	if err != nil {
		return poolResult{}, fmt.Errorf("create pool store: %v", err)
	}

	var res poolResult
	seen := make(map[c4.ID]bool)

	for _, e := range m.Entries {
		if e.C4ID.IsNil() || seen[e.C4ID] {
			continue
		}
		seen[e.C4ID] = true

		if dst.Has(e.C4ID) {
			res.Skipped++
			continue
		}

		rc, err := src.Open(e.C4ID)
		if err != nil {
			res.Missing++
			continue
		}

		if _, err := dst.Put(rc); err != nil {
			rc.Close()
			return res, fmt.Errorf("store %s: %v", e.C4ID, err)
		}
		rc.Close()
		res.Copied++
	}

	// Copy the c4m file
	c4mDest := filepath.Join(outDir, filepath.Base(c4mPath))
	if err := copyFile(c4mPath, c4mDest); err != nil {
		return res, fmt.Errorf("copy manifest: %v", err)
	}

	// Generate self-extracting script
	if err := writeExtractScript(outDir, filepath.Base(c4mPath), m); err != nil {
		return res, fmt.Errorf("write extract.sh: %v", err)
	}

	return res, nil
}

// copyFile copies a regular file.
func copyFile(src, dst string) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0755); err != nil {
		return err
	}
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()

	if _, err := io.Copy(out, in); err != nil {
		return err
	}
	return out.Sync()
}

// writeExtractScript generates a portable shell script that materializes
// the c4m contents using only standard Unix tools — no c4 installation required.
// All paths are shell-escaped to prevent injection from malicious entry names.
func writeExtractScript(outDir, c4mName string, m *c4m.Manifest) error {
	scriptPath := filepath.Join(outDir, "extract.sh")
	f, err := os.OpenFile(scriptPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0755)
	if err != nil {
		return err
	}
	defer f.Close()

	safeName := shellEscape(strings.TrimSuffix(c4mName, ".c4m"))

	fmt.Fprintf(f, "#!/bin/sh\n")
	fmt.Fprintf(f, "# Self-extracting script generated by c4sh pool.\n")
	fmt.Fprintf(f, "# No c4 installation required.\n")
	fmt.Fprintf(f, "# Not using set -e: missing store objects should warn, not abort.\n")
	fmt.Fprintf(f, "DIR=\"$(cd \"$(dirname \"$0\")\" && pwd)\"\n")
	fmt.Fprintf(f, "STORE=\"$DIR/store\"\n")
	fmt.Fprintf(f, "OUT=\"${1:-./%s}\"\n", safeName)
	fmt.Fprintf(f, "echo 'Extracting to '\"$OUT\"' ...'\n")

	// Build directory creation commands and file copy commands
	var dirStack []string
	for _, e := range m.Entries {
		fullPath := shellEscape(buildPath(dirStack, e))

		if e.IsDir() {
			for len(dirStack) > e.Depth {
				dirStack = dirStack[:len(dirStack)-1]
			}
			dirStack = append(dirStack, strings.TrimSuffix(e.Name, "/"))
			fmt.Fprintf(f, "mkdir -p \"$OUT\"/%s\n", fullPath)
			continue
		}

		if e.C4ID.IsNil() {
			continue
		}

		// C4 IDs are base58 only (safe for shell), find in store trie
		idStr := e.C4ID.String()
		fmt.Fprintf(f, "SRC=$(find \"$STORE\" -name '%s' -print -quit 2>/dev/null)\n", idStr)
		fmt.Fprintf(f, "if [ -n \"$SRC\" ]; then cp \"$SRC\" \"$OUT\"/%s; else echo \"warning: missing %s\" >&2; fi\n", fullPath, idStr)
	}

	fmt.Fprintf(f, "echo 'Done.'\n")
	return nil
}

// shellEscape wraps a string in single quotes, escaping any embedded single
// quotes with the '\'' idiom. This is safe for POSIX sh.
func shellEscape(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'"
}

// buildPath reconstructs a file path from the directory stack and entry.
func buildPath(dirStack []string, e *c4m.Entry) string {
	parts := make([]string, 0, len(dirStack)+1)
	for i := 0; i < e.Depth && i < len(dirStack); i++ {
		parts = append(parts, dirStack[i])
	}
	parts = append(parts, strings.TrimSuffix(e.Name, "/"))
	return path.Join(parts...)
}
